config/routes.rb
Coolshop::Application.routes.draw do
  resources :line_items

  resources :carts

  resources :products
    resources :orders


  root to: 'products#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product
  belongs_to :order
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  belongs_to :product

  attr_accessible :comment, :email, :name, :phonenumber

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
            :length   => { :maximum => 50 }

  validates :email, :presence => true,
            :format   => { :with => email_regex }

  validates :phonenumber, :presence => true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price
  has_many :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def index
    @line_items = LineItem.all
  end

  def show
    @line_item = LineItem.find(params[:id])
  end

  def new
    @line_item = LineItem.new
  end

  def edit
    @line_item = LineItem.find(params[:id])
  end

  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.line_items.build(product: product)

    if @line_item.save
      redirect_to @line_item.cart, notice: t('notices.success_item_add')
    else
      render "new"
    end
  end

  def update
    @line_item = LineItem.find(params[:id])
      if @line_item.update_attributes(params[:line_item])
        redirect_to @line_item, notice: 'Line item was successfully updated.'
      else
        render "edit"
      end
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to line_items_url
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to root_path, notice: t('notices.empty_cart')
      return end
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    @order.add_line_items_from_cart(current_cart)
    if @order.save
      redirect_to root_path, notice: t('notices.success_order')
    else
      render :action => "new"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.paginate(:page => params[:page], per_page: 6)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_form.html.haml
= simple_form_for(@cart) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
%h2 Your Cart
%ul
  - @cart.line_items.each do |item|
    %li= item.product.name
= button_to "Checkout", new_order_path, class: "small button", method: :get
= link_to 'вернуться к просмотру продуктов', root_path, class: "small button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title CoolShop
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .row
      .twelve.columns
        .panel
          %h3{:style => "text-align: center;"} Куча одинаковой херни по 999 баксов
      .twelve.columns
        - if notice
          .alert-box.success= notice
        - if alert
          .alert-box.alert= alert
        = yield

app/views/line_items/_form.html.haml
= simple_form_for(@line_item) do |f|
  = f.error_notification

  .form-inputs
    = f.input :product_id
    = f.input :cart_id

  .form-actions
    = f.button :submit

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %tr
    %th Product
    %th Cart
    %th
    %th
    %th

  - @line_items.each do |line_item|
    %tr
      %td= line_item.product_id
      %td= line_item.cart_id
      %td= link_to 'Show', line_item
      %td= link_to 'Edit', edit_line_item_path(line_item)
      %td= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product_id
%p
  %b Cart:
  = @line_item.cart_id

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path

app/views/orders/new.html.haml
.six.columns.centered
  %h4 Your Order
  .panel
    = simple_form_for @order do |f|
      = f.input :name, label: "Name", as: :tel
      %br
      = f.input :email, label: "Email", placeholder: "user@domain.com"
      %br
      = f.input :phonenumber, label: "Phone Number"
      %br
      = f.input :comment, label: "Commentaries", as: :tel
      %br
      = f.button :submit, class: "small button"

app/views/products/_product.html.haml
%li
  .panel
    = image_tag( asset_path('1.jpeg'), size: "170x170", alt: product.name )
    %br
    %b Name:
    = product.name
    %br
    %b Price:
    = product.price
    $
    %br
    = link_to 'подробнее', product, class: "small button"
    = button_to "Add to Cart", line_items_path(product_id: product), class: "small button"

app/views/products/index.html.haml
.four.columns.centered
  %h3{:style => "text-align: center;"} Продукты
  = will_paginate
.row
  .twelve.columns.centered
    .panel
      %ul.block-grid.three-up
        -@products.each do |product|
          = render product
.four.columns.centered
  = will_paginate

app/views/products/show.html.haml
.row
  .twelve.columns
    .panel
      %h5= "Подробнее о: #{@product.name}"
      .row
        .four.columns
          .panel
            = image_tag( asset_path('1.jpeg'), size: "200x200", alt: @product.name )
        .four.columns
          .panel
            %br
            %b Name:
            = @product.name
            %br
            %b Description:
            = @product.description
            %br
            %b Price:
            = @product.price
            $
            %br
            = button_to "Add to Cart", line_items_path(product_id: @product), class: "small button"
= link_to 'вернуться к просмотру продуктов', root_path, class: "small button"